### ISSUE TITLE
Webview drop event never fired

### ISSUE THREAD

**Issue by ibdknox** [atom/atom-shell#1276]
For non-file drops, the drop event is never fired in a webview. As a simple repro, load: http://www.html5rocks.com/en/tutorials/dnd/basics/ in a webview scroll to the bottom and try dragging and dropping some of the boxes. The drags work, but drop is never fired.

**Comment by zcbenz** [comment]
We had the same bug (#908) before but it was solved with a workaround, can you see whether it also solves your problem?

In the [original Chromium bug](https://code.google.com/p/chromium/issues/detail?id=412373) someone also posted a workaround.

**Comment by ibdknox** [comment]
Thanks to the pointer to the original chromium bug. For those wondering, you have to explicitly set the text datatype to get it to work. We set others, but didn't have text. Doing so appears to "fix" it.

```javascript
event.dataTransfer.setData("text", ...);
```

Definitely a workaround, but it works. :) Thanks!

**Comment by jdsimcoe** [comment]
@ibdknox I followed some instructions in #908 but I still can't get the drop event to work correctly. The code I added below keeps the app from being taking over by an image upload when it is dragged into the app window:

```js
   webView.addEventListener('new-window', function (e) {
        webView.src = e.url;
    });
    document.addEventListener('drop', function(e) {
        e.preventDefault();
        e.stopPropagation();
    });
    document.addEventListener('dragover', function(e) {
        e.preventDefault();
        e.stopPropagation();
    });
    webView.addEventListener('dragover', function(e) {
        e.preventDefault();
    });
    webView.addEventListener('drop', function(e) {
        e.preventDefault();
    });
```
I still can't get `drop` to pass through to my `<webview>`. Any ideas of how I would need to modify my code to accomplish this?

**Comment by jacobmischka** [comment]
@jdsimcoe To prevent the app window from being taken over by the image, you can catch the `will-navigate` event.

```
mainWindow.webContents.on('will-navigate', function(event){
	event.preventDefault();
});
```

That won't fix the problem you're currently having I don't believe, to fix that you'll need to do the 
```
event.dataTransfer.setData("text", ...);
```
~~fix~~ workaround that was mentioned earlier in this thread.

**Comment by jacobmischka** [comment]
On a related note, @ibdknox can you please tell me where I should put the event handler? The webview confuses me. Should it be on the items that are being dragged, or the webview, or webcontents, or none of those?

**Comment by rodrigok** [comment]
@jacobmischka worked for me putting the code at the "server side" where you create the browser window.

```javascript
    mainWindow = new BrowserWindow({
        x: mainWindowState.x,
        y: mainWindowState.y,
        width: mainWindowState.width,
        height: mainWindowState.height
    });

    mainWindow.webContents.on('will-navigate', function(event) {
        event.preventDefault();
    });
```

**Comment by jacobmischka** [comment]
Oh, sorry, I was asking for the event handler for the "dragstart" event.

**Comment by rodrigok** [comment]
@jacobmischka oh, ok, :smile: 

As my problem is with file upload using drag&drop from OS my problem was solved blocking the navigation only.

**Comment by jacobmischka** [comment]
Yeah, file upload is working for me now, but there are some elements within the webview that want to be dragged to reordered, and they still don't work.

**Comment by alexstrat** [comment]
How did you guys manage to make this work when you don't have control on how the `dragstart` event is handled. I mean, I load external content in the webview and I don't have control on `dragstart` event listener to `event.dataTransfer.setData("text", ...);`.

For instance how would you make http://www.html5rocks.com/en/tutorials/dnd/basics/ work when loaded in a webview?
